name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  package_aws:
    name: Package AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf Fleurden.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        source: "Fleurden.war"
        target: "/opt/tomcat/webapps"
  sav_ipfs:
    needs: package_aws
    name: SAV IPFS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          jar cvf Fleurden.war *
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier war sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add Fleurden.war
        shell: alpine.sh --root {0}

  upload_dump:
    name: Upload Dump
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: |
          apk add mysql mysql-client
          ssh -i ${{ secrets.EC2_SSH_KEY }} admin@ec2-13-37-215-179.eu-west-3.compute.amazonaws.com -fN -L 0.0.0.0:3307:127.0.0.1:3306
          apk add go-ipfs
          ipfs init
          ipfs daemon &
        shell: alpine.sh --root {0}
      - name: Sauvegarde fichier dump sur IPFS
        run: |
          ls -la 
          ipfs swarm peers
          ipfs add sauvegarde_films.sql
        shell: alpine.sh --root {0}
